export const INTERNSHIPS = [
  {
    id: 'tf-frontend',
    role: 'Frontend Developer Intern',
    company: 'TechFlow Systems',
    location: 'Bangalore, India',
    stipend: '₹25,000 / mo',
    type: 'Internship',
    duration: '3 Months',
    mode: 'Remote',
    posted: '2 days ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=TF',
    tags: ['React', 'TypeScript', 'CSS'],
    sector: 'software',
    verified: true,
    fastTrack: true,
    employeeCount: '200-500',
    companylink: '#',
    description: 'Build modern UI features with the product engineering team.',
    generalMatch: 86,
  },
  {
    id: 'ih-data',
    role: 'Data Analyst Intern',
    company: 'InsightHive',
    location: 'Gurgaon, India',
    stipend: '₹26,000 / mo',
    type: 'Internship',
    duration: '4 Months',
    mode: 'Hybrid',
    posted: '1 week ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=IH',
    tags: ['SQL', 'Python', 'Excel'],
    sector: 'data',
    verified: true,
    fastTrack: false,
    employeeCount: '50-200',
    companylink: '#',
    description: 'Support analytics, reporting, and dashboarding for growth teams.',
    generalMatch: 78,
  },
  {
    id: 'so-cyber',
    role: 'Cybersecurity Analyst Intern',
    company: 'ShieldOps',
    location: 'Delhi NCR, India',
    stipend: '₹27,000 / mo',
    type: 'Internship',
    duration: '6 Months',
    mode: 'Onsite',
    posted: '3 days ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=SO',
    tags: ['Linux', 'Networking', 'SIEM'],
    sector: 'cyber',
    verified: true,
    fastTrack: true,
    employeeCount: '100-300',
    companylink: '#',
    description: 'Assist the SOC with alert triage and vulnerability scans.',
    generalMatch: 72,
  },
  {
    id: 'np-fullstack',
    role: 'Full Stack Developer Intern',
    company: 'NovaPath Labs',
    location: 'Pune, India',
    stipend: '₹28,000 / mo',
    type: 'Internship',
    duration: '6 Months',
    mode: 'Hybrid',
    posted: '4 days ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=NP',
    tags: ['React', 'Node.js', 'MongoDB'],
    sector: 'software',
    verified: true,
    fastTrack: true,
    employeeCount: '100-250',
    companylink: '#',
    description: 'Ship features across web frontend and Node APIs in an agile squad.',
    generalMatch: 81,
  },
  {
    id: 'ql-ml',
    role: 'ML Engineering Intern',
    company: 'QuantLeaf AI',
    location: 'Hyderabad, India',
    stipend: '₹30,000 / mo',
    type: 'Internship',
    duration: '5 Months',
    mode: 'Remote',
    posted: '5 days ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=QL',
    tags: ['Python', 'ML', 'PyTorch'],
    sector: 'data',
    verified: true,
    fastTrack: false,
    employeeCount: '50-150',
    companylink: '#',
    description: 'Prototype models, evaluate metrics, and support production ML pipelines.',
    generalMatch: 74,
  },
  {
    id: 'cx-cloud',
    role: 'Cloud & DevOps Intern',
    company: 'CloudNest',
    location: 'Mumbai, India',
    stipend: '₹24,000 / mo',
    type: 'Internship',
    duration: '3 Months',
    mode: 'Onsite',
    posted: '6 days ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=CN',
    tags: ['AWS', 'Docker', 'Linux'],
    sector: 'software',
    verified: true,
    fastTrack: false,
    employeeCount: '200-400',
    companylink: '#',
    description: 'Help maintain CI/CD pipelines and cloud infrastructure with the platform team.',
    generalMatch: 69,
  },
];
